services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: schedulator-pswd
    shm_size: 128mb
    ports:
      - "5431:5432"
    volumes:
      - schedulator_db:/var/lib/postgresql/data/

  schedulator:
    links:
      - db
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VERSION=latest

    # restart: always
    ports:
      - "3001:3000"

#  adminer:
#    image: adminer
#    restart: always
#    ports:
#      - 8080:8080
volumes:
  schedulator_db: {}
