services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: schedulator-pswd
    shm_size: 128mb
    volumes:
      - schedulator_db:/var/lib/postgresql/data/
    networks:
      schedulator:
        ipv4_address: 172.19.0.2

  schedulator:
    links:
      - db
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VERSION=latest
    networks:
      schedulator:
        ipv4_address: 172.19.0.3
    restart: always
    ports:
      - "3000:3000"

#  adminer:
#    image: adminer
#    restart: always
#    ports:
#      - 8080:8080

volumes:
  schedulator_db: {}
  
networks:
  schedulator:
    driver: bridge
    ipam:
      config:
      - subnet: 172.19.0.0/16
      driver: default

