name: Build app

on:
  push:
    tags:
      - '**'

env:
  CARGO_TERM_COLOR: always

jobs:
  build_rust_linux:
    name: Linux - Rust app
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - run: cargo build --release
      - run: mv ./target/release/server ./target/release/schedulator
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifact-rust-linux
          retention-days: 1
          path: |
            ./target/release/schedulator
            ${{ steps.compile.outputs.BUILT_ARCHIVE }}
            ${{ steps.compile.outputs.BUILT_CHECKSUM }}
  
  build_web_app:
    name: Web app
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - working-directory: ./webclient
        run: npm install
      - working-directory: ./webclient
        run: npm run prod
      - uses: actions/upload-artifact@v4
        with:
          name: webapp-artifact
          retention-days: 1
          path: ./webclient/public/*

  package:
    name: Upload release
    runs-on: ubuntu-22.04
    needs: [build_rust_linux, build_web_app]
    steps:
      - uses: actions/checkout@v2
      
      # Download generated artifacts
      - name: Retrieve artifact Rust/Linux
        uses: actions/download-artifact@v4
        with:
          name: artifact-rust-linux
          path: ./artifact_rust_linux

      - name: Retrieve artifact Web app
        uses: actions/download-artifact@v4
        with:
          name: webapp-artifact
          path: ./artifact_web_app/public

      # Create Docker setup zip
      - run: zip -r docker.zip ./docker/

      # Create Linux server zip
      - run: mkdir schedulator/
      - run: mkdir schedulator/migrations/
      - run: mv ./artifact_rust_linux/schedulator ./schedulator/
      - run: cp -r ./migrations/* ./schedulator/migrations
      - run: cp -r ./artifact_web_app/* ./schedulator/
      - run: zip -r schedulator_linux.zip ./schedulator/
      - run: rm -r ./schedulator/

      # Generate changelog
      - run: '{"changelog_type":'
      - run: echo '{"changelog_type": "commit_message", "commit_changelog": true, "comment_changelog": true}' > changelog-ci-config.json
      - name: Run Changelog CI
        uses: saadmk11/changelog-ci@v1.1.2
        with:
          config_file: changelog-ci-config.json
          release_version: ${{ github.ref_name }}
          changelog_filename: ${{ github.workspace }}-CHANGELOG.md

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          body_path: ${{ github.workspace }}-CHANGELOG.md
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            schedulator_linux.zip
            docker.zip
