name: Build app

on:
  push:
    tags:
      - '**'

env:
  CARGO_TERM_COLOR: always

jobs:
  build_rust_linux:
    name: Linux - Rust app
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@main
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - run: cargo build --release
      - run: mv ./target/release/server ./target/release/schedulator
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifact-rust-linux
          retention-days: 1
          path: |
            ./target/release/schedulator
            ${{ steps.compile.outputs.BUILT_ARCHIVE }}
            ${{ steps.compile.outputs.BUILT_CHECKSUM }}

  package:
    name: Upload release
    runs-on: ubuntu-22.04
    needs: [build_rust_linux]
    steps:
      # Download generated artifacts
      - name: Retrieve artifact Rust/Linux
        uses: actions/download-artifact@main
        with:
          name: artifact-rust-linux
          path: ./artifact_rust_linux

      # Create Linux server zip
      - run: mkdir schedulator
      - run: mv ./artifact_rust_linux/schedulator ./schedulator/
      - run: zip -r schedulator_linux.zip ./schedulator/
      - run: rm -r ./schedulator

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            schedulator_linux.zip
